### ISSUE TITLE
Page section allows multiple blocks?

### ISSUE THREAD

**Issue by notflip** [wernerglinka/ruhrpott-studio#1]
Thanks for sharing this repo! Is it by design that inside a section, multiple page blocks can be added?

![Screenshot 2024-03-17 at 06 37 59](https://github.com/wernerglinka/ruhrpott-studio/assets/4146384/2cb2c97b-d812-41d8-9d8f-c25d2832bc78)

**Comment by wernerglinka** [comment]
Hi Miguel,
Yes, that is by design. For this Proof of Concept, I used single blocks for a section for simplicity, but you can use multiple blocks. Of course, that would require additional layouts. For example, I use a section called media, which is composed of text, a CTA and an image. That could also be done with individual blocks. If you want to learn more about this approach, please see https://metalsmith-components.netlify.app/. 
Any questions just asked, I am happy to elaborate.
Werner

**Comment by notflip** [comment]
Thanks @wernerglinka I've been experimenting with Sanity all weekend and I love it, I mostly use Directus, but Sanity feels more mature. And I love that the studio is all code.  Thanks for sharing this code, it's been helpful
